application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "lrzcc"
openstack:
  # admin credentials
  username: "USERNAME"
  password: "PASSWORD"
  project: "PROJECT"
  project_id: "PROJECT_ID"
  domain: "DOMAIN"
  domain_id: "DOMAIN_ID"
  keystone_endpoint: "https://cc.lrz.de:5000"
  nova_endpoint: "https://cc.lrz.de:8774"
