[workspace]
resolver = "2"
members = [
    "api",
    "lib",
    "cli"
]

[workspace.dependencies.cargo-husky]
version = "1.5"
default-features = false
features = [ "run-for-all", "prepush-hook", "run-cargo-check", "run-cargo-test", "run-cargo-clippy", "run-cargo-fmt" ]
