[workspace]
resolver = "2"
members = [
    "api",
    "lib",
    "cli",
    "wire",
    "test",
]

[workspace.dependencies.cargo-husky]
version = "1.5"
default-features = false
features = [ "user-hooks" ]
