name: audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/audit.yml'
      - 'deny.toml'
      - 'Cargo.toml'
      - '**/Cargo.toml'
      - 'Cargo.lock'
      - '**/Cargo.lock'
    branches: [ main ]

permissions: {}

jobs:

  advisories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@v2.49.37
        with:
          tool: cargo-deny
      - name: check advisories
        run: cargo deny check advisories

  bans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@v2.49.37
        with:
          tool: cargo-deny
      - name: Scan for vulnerabilities
        run: cargo deny check bans

  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@v2.49.37
        with:
          tool: cargo-deny
      - name: check licenses
        run: cargo deny check licenses

  sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@v2.49.37
        with:
          tool: cargo-deny
      - name: check sources
        run: cargo deny check sources
