name: labeler
on: [pull_request]
# NOTE: zizmor marks this as insecure, it's only necessary for forked PRs
# on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Check out repository code
      uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Label the PR
      uses: actions/labeler@v6
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
