name: lint

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches:
      - 'main'
    paths:
      - '**/src/**/*'
      - '**/tests/**/*'
      - 'Cargo.toml'
      - '**/Cargo.toml'
      - 'Cargo.lock'
      - '**/Cargo.lock'
      - '.rustfmt.toml'
      - 'docker-compose.yml'
      - '.github/workflows/lint.yml'

permissions: {}

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: "0.8.6"

jobs:
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo +nightly fmt --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: getong/mariadb-action@v1.11
        with:
          mariadb version: '10.6.21'
          mysql database: 'avina'
          mysql root password: 'password'
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          key: sqlx-${{ env.SQLX_VERSION }}
      - name: Install mold
        run: sudo apt update && sudo apt install mold -y
      - name: Run clippy
        run: SQLX_OFFLINE=true cargo clippy --all --all-targets -- -D warnings

  spellcheck:
    name: spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@v2.62.36
        with:
          tool: cargo-spellcheck
      - name: Check spelling
        run: cargo spellcheck --cfg=.spellcheck.toml --code 1

  machete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Machete
        uses: bnjbvr/cargo-machete@main
